version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: fastapi dev main.py --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  worker:
    build: ./backend
    command: rq worker
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
