"""Add filename column to jobs table

Revision ID: 17fd78f77dc0
Revises: 0b8b66b6cd9d
Create Date: 2026-04-04 11:53:43.165373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17fd78f77dc0'
down_revision: Union[str, Sequence[str], None] = '0b8b66b6cd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'filename')
    # ### end Alembic commands ###
