"""Add s3_url column to jobs table

Revision ID: 8e851beaf434
Revises: 17fd78f77dc0
Create Date: 2026-04-05 19:11:24.031207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e851beaf434'
down_revision: Union[str, Sequence[str], None] = '17fd78f77dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('s3_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 's3_url')
    # ### end Alembic commands ###
